---
title: "PSYC422 2026 Grades For Examiners' Meeting"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
    social: menu
runtime: shiny
---

```{r global, include=FALSE}
# load data and call packages in 'global' chunk so it can be shared by all users of the dashboard
library(dplyr)
library(readr)
library(ggplot2)
library(plotly)
library(rcartocolor)
library(kableExtra)
library(summarytools)
library(ggExtra)
library(ggpubr)
library(shiny)
library(flexdashboard)
library(psych)
library(fansi)

# read in grades 
grades <- read_csv("2026 TRIMESTER 1 PSYC422 Grades.csv")

grades <- grades %>%  # rename columns to be more concise for display 
  rename(
   
    DB=  `Discussion Board`, 
 
  )

grades$Grade <- factor(grades$`Letter grade`,levels = c("P", "C", "D", "HD", "NC", "NI", "SPE/SET", "SPE"))

gradesForSummary <- select(grades, Quiz, DB, Assignment, Exam, Total) # select only the ones we want for the summary section

gradesForSummary <- gradesForSummary[complete.cases(gradesForSummary), ] # Remove rows with NAs. 
```

## Column {.sidebar}

```{r sidebar}
# Set up where we select the input
selectInput('xcol', 'X Variable', names(gradesForSummary), 
            selected=names(gradesForSummary)[[3]])
    
selectInput('ycol', 'Y Variable', names(gradesForSummary),
                selected=names(gradesForSummary)[[4]])
```

## Column

### Correlations

```{r correlations interactive}

# Combine the selected variables into a new data frame
selectedData <- reactive({
  gradesForSummary[, c(input$xcol, input$ycol)]
})

# plot the data
renderPlot({
  par(mar = c(5.1, 4.1, 0, 1)) # plot parameters
  p <- ggplot(selectedData(), aes_string(x=input$xcol, y=input$ycol)) + # use selected data
    geom_point(color="red", size = 3)+ # plot points on the scatter plot 
    geom_smooth(method=lm,color="red")+ theme_classic() +  # fit regression line using geom_smooth
    stat_cor(method = "spearman", digits = 2, size = 7) + # display correlation on plot using stat_cor
    theme(text = element_text(size = 20)) # scale up text 
 p1 <- ggExtra::ggMarginal(p, type = "histogram", fill = "grey" ) # plot marginal histograms using ggextra 
  print(p1)})

```

## Outputs

### Grade distributions

```{r grade distributions}
# Bar plot with letter grade distributions
l <- ggplot(data=grades, aes(x=Grade, fill=Grade)) + 
    scale_fill_carto_d(name = "Grade ",  palette = "Safe")+
    geom_bar()+ ggtitle("Letter grades")

# use ggplotly to make plot interactive
ggplotly(l)

```

### Summary table

```{r summary table}

# rename variables with percentages for display
gradesForSummary1 <- gradesForSummary %>% 
  rename(
    `Quiz component (10%)` = `Quiz`,
    `Assignment (30%)` = `Assignment`,
   `Discussion Board (10%)` =  `DB`, 
    `Final Exam (50%)`=  `Exam`,
    Total = Total
  )

# Make a descriptive results table using summarytools

#ResultsTable <- descr(gradesForSummary1, stats = c("mean", "min", "max", "sd"), 
                     # transpose = TRUE, headings = FALSE)

tab1 <- describe(gradesForSummary1, fast = TRUE)

tab1 <- select(tab1, n, mean, sd, median, min, max) # select only the ones we want for the summary section

# display table using kableextra
tab1%>%
  kable(caption = "Overall Results Summary", digits = 2) %>%
  kable_styling()
```
